# Becoming a better business analyst

Jinyu Wang and Shuai Yuan

As our community contribution, we wrote an article on becoming a better business analyst based on our own experience in the industry. The full article can be found here: <https://github.com/jw4044/article-business-analyst/blob/main/5702contribution.pdf>

Main Goal:

The main goal of the project is to give everyone some advice on some core information about business analytics and data analysis. Also, we will include some advice on how to become a better business analyst based on our own experience. Since the job market is pretty bad these days, we think we should share some decent advice and help all of us improve together. We included three tips in detail:

1\. Proactive application of data science methods helps me to be more productive, giving me more time to work on things that matter.

2\. Applying some data science methods can help to get more accurate analysis results and create higher business value.

3\. When you practice your coding skills, outperform the job requirements, and use proactive data analysis to optimize daily jobs, you will stand out in the interview process.

Evaluation:

By completing this article, we fully summarized our internship experiences and rethought the good and bad steps we took. We learned from each other and it helped us to know what we individually lack in the current step and we both have better future planning on becoming better data analysts or using data analysis skills. For the evaluation, we think it will be better if we can share more detail and visualize our project we have done, so that other people can see more clearly.
