# Data importance & visualization

Utsav Vachhani

## Description:
This document is a collection of my thoughts on importance of data visualization in a blog post format. In the article, I go through a brief history of how data visualization came around to be and what purpose it has served. Additionally, I connect it to how it is utilized today and the present some use cases. The blog is intended for non-technical users, so I also introduce some fundamental graphs that are common in data visualizations. Finally, I touch on some negative uses of data visualization in recent times and analyze instances to alert the audience to be on the lookout. 

## Motivation: 
Data visualization has always been interesting to me as I come from a business background. It serves as a great complement to the rigorous analysis and experimentation done in data science and, gives us a concise way to show insights through appealing visualizations. I also like that it introduces a creative and artistic component to an otherwise analysis heavy workload. I noticed that sometimes professionals, especially ones interested in data science or related fields, focus a lot on getting results but not enough time to translate them properly. I want this blog to showcase that data visualization is very influential today since a lot of people will believe everything they see online without proper research. Therefore, it is more imperative to at least know the basics to identify inaccuracies when shown. When I have a completed personal website, I am planning to include this blog as an article to highlight the significance of data visualization. 


[Link to pdf](https://github.com/utsavkv/EDAV_CC/blob/main/EDAV_FinalCC.pdf){target="_blank"}