# EDAV Survey and Analysis
Varalika Mahajan and Vrinda Bhat

### Project Proposal

#### Project Group: CC5

Varalika Mahajan: vm2695

Vrinda Bhat: vgb2113

#### Visualization Preference Analysis

##### Overview

Form Link: https://forms.gle/SYKeS6fqGktr5qrN8

No of responses: 80

Data Collected: https://docs.google.com/spreadsheets/d/1apWvWCVmk4donteDaWEuMjDvHc1gJZxfrbSXeILNJyE/edit?usp=sharing

Full Document Link: https://docs.google.com/document/d/1RKa9HXl6icDS5ci4K7oLATZjFOp4oWNzELslTATMJL8/edit?usp=sharing

##### Goals:

To understand people’s opinions on different visualizations: Different views on graphs and visualizations help us to understand their importance and the structural necessity of existing and most-used graphs.

Validate if factors like age, work experience, and gender impact their opinion:  Usually applying the learned classroom concepts to real-life work-related problems gives us a better understanding of what is more meaningful for business insights. Thus, we checked if factors like experience, age, and gender showed a huge impact on choices.

