# googleVis

Wenqi Sun

The googleVis package provides an interface between R and the Google's charts tools. It allows users to create web pages with interactive charts based on R data frames. Charts are displayed locally via the R HTTP help server. A modern browser with Internet connection is required. The data remains local and is not uploaded to Google.

I created a cheat sheet for googleVis. It covers most charts and some options.

Link: https://github.com/Nntraveler/googleVis_cheatsheet/blob/main/googleVis.pdf

## Motivation for this project

Google Charts is a powerful tool for the visualization of HTML. It provides an easy and quick way to generate interactive charts. 

The advantages include the following:

- A variety of charts

- Extensive set of options for customization

- Cross-browser compatibility

- Dashboard and Controls for user interaction

- Support dynamic data

The googleVis package provides a way to use Google charts with R conveniently. Although it has detailed documentation, users may need clarification about which chart and options work for their cases since there is no cheat sheet.

Therefore, by creating the cheat sheet for googleVis, everyone can get it easier to use googleVis.

## My own evaluation of the project

After creating the cheatsheet, I

- have a better understanding of Google charts and googleVis package

- experienced happiness for contributing something to the open source projects

- explored a variety of cheatsheets and found an ideal layout for my project

What's more, I think there is some space for improvement:

- For the options part, it could be a better way to show how to use these options vividly. Due to limited space, I just put a table here.

- The compressed charts look bad for some charts like Anno, Cal, and Timeline charts. I could assign more space or adjust the data.
