# Tutorial on Machine Learning in R

Priyanka Balakumar and Hao Pan

## Introduction
Machine learning is a branch in computer science that studies the design of algorithms that can learn. Within machine learning, there exists three main categories: supervised learning, unsupervised learning, and reinforcement learning. This ‘Machine Learning in R’ cheat sheet explores some basic supervised and unsupervised machine learning techniques.  

## Motivation
There are several advantages to implementing machine learning using R. Firstly, R provides easily explainable code which is especially helpful for those starting out in machine learning and needing to explain their code. In addition, R is the perfect language for easy data visualization. There are corresponding functions for different machine learning techniques that allow a user to visualize and understand performance results.  

Here is the link to the cheatsheet:  
https://github.com/Stephen-Pan30/EDAV-CommunityContribution/blob/main/Machine%20Learning%20Cheatsheet.pdf
