#  Cheatsheet for Plotly

Taichen Zhou, Yichen Huang

For the community contribution for the EDAV class, we researched and created an R graphing library - plotly which can create integrative, publication-quality graphs. In this cheat sheet, we will provide the example of how to create basic charts, statistical charts, scientific charts etc. with Plotly.
The link of the cheat sheet is [here](https://yichuang25.github.io/Plotly-Cheatsheet/).

## Motivation
Data visualization is a crucial part for data scientist. As the tech industry matures, the demand for better visualizations increases. Each type of visualization has its specialty, just like a line chart describes trend better than a bar plot. To display data in an extraordinary fashion, Plotly is insanely powerful at explaining and exploring data. And here is the reason why.

### Interactivity
Plotly provides a feature that no other visualization library has — interactivity. Plotly allows users to further improve the visualization experience by using customizable interactive tools. When we visualize data with Plotly, we can add interactive features like buttons, sliders, and dropdowns to display different perspectives of graphs.

### Customization and Flexibility
Plotly is like a piece of paper, you can draw whatever you want on it. Compared to traditional visualization tools like ggplot2, Plotly allows full control over what is being plotted.

## Evaluation and Future Improvement
By making this Plotly cheat sheet, we learned how to not only graph in which we have talked about in ggplot, but also graph used in Machine Learning for example, ROC and PCA visualization. Also, we got more familiar with writing in R markdown file. 
There are still things we can furtherly improve, like we can add more types of graphs in our cheat sheet for example, alluvia plot. Moreover, the introduction of parameters of functions to plot the graph can be talked about a little bit more.
