# Video guide to reigniting your creavite spark for visualizations 
Imani Oluwafumilayo Maliti 

## Video 

<iframe width="560" height="315" src="https://www.youtube.com/embed/Q4CwEbKsBsQ" data-external= "1" allowfullscreen></iframe>

<br />
In the situation where the embedded does not work for your device, the following is a link to the same video: https://youtu.be/Q4CwEbKsBsQ
<br />

<strong> Note: For those who are hard of hearing or simply prefer subtitles, the embedded video and the YouTube video have both been equipped with Closed Captioning to make your viewing experience more accessible to you. </strong> 

## Motivation & Explanation

My orig inal motivation for this project was to brainstorm viables activities that people could partake in to reignite their creative spark while creating data visualizations. By culture, I am a storyteller—and I have always viewed data visualizations as a prime, modern way of storytelling. By trade, I am a content creator. I specialize in editing videos and creating graphics that not only convey a story, but that inspire people to do something great with their lives. Naturally, when I visualize data, I try to incorporate both the artistic and cultural aspects of my training. I strive to make accessible visualizations that are also fun, engaging, and intentional; however, I have been in many spaces with data scientists that do not prioritize such creativity. Although I understand the importance of practicality and “professionalism”, I strongly believe that having a creative mindset is a major strength. As a result, I created a video in which I explain three activities that can aid in one’s journey to making more creative visualizations.<br />
<br />
Originally, I wanted to make a video in the form of a Tik Tok. My hope was to share it on the platform to make this information more accessible to the community who needs it and boost its impact. However, I found myself with over 20 minutes of content that I had to cut down, edit, and piece together. Ultimately, I was left with my final 6 minute video—which is too long to post on Tik Tok. If I did have to re-do this project, I would have done a shorter video; in turn, this would have enabled me to post it. To compensate for the missing information and explanations, I would pair said video with a blog post that goes into further detail about each activity. Other than that, I feel like the video came out pretty well and I am proud of the final products.


## Resources
B., Du Bois William E, et al. W. E. B. Du Bois's Data Portraits: Visualizing Black America. W.E.B. Du Bois Center at the University of Massachusetts Amherst, 2018.<br/>
<br/> “THE BOOK.” Dear Data, http://www.dear-data.com/thebook.