# Two Interesting R packages

Shiyuan Xu and Ying Hong

As our community contribution, we made a demonstration on two exciting R packages called "cowsay" and "fortunes". 

The link to the Shiny app can be found here:
https://shiyuan-xu.shinyapps.io/cc_xu_ying/

The link to the Rmd file can be found here:
https://github.com/ShiyuanXu/Stats5702_CC

## Motivation
As we learned in this class, R is a powerful tool to analyze and visualize data. However, sometimes when we get bored with R, we started to question what else R can do and what interesting packages that R has. Therefore, we started to explore a few fun packages in R— “cowsay” and “fortunes”.
In the project, we included some detailed explanations of what the packages do and how to use the arguments to control output. Afterward, we make a fun interactive tool using shiny to combine the two packages and the link is attached above (as an interactive file cannot render a meaningful HTML). 

## Evaluation
From this project, besides the contents of the package, we learned that coding can be fun and fascinating. Next time we would like to introduce more intriguing packages into our demo and create a more interesting interactive game.